import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>
}>) => {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased  min-h-[125vh] `}
        
      >
        <Providers locale={(await params).locale}>
          {children}
        </Providers>

      </body>
    </html>
  );
}

export default RootLayout;